### ISSUE TITLE
Can't encrypt stream objects (StringIO, BytesIO, etc.)

### ISSUE THREAD

**Issue by garrettr** [isislovecruft/python-gnupg#89]
**POC**

```py
$ python
Python 2.7.6 (default, Mar 22 2014, 22:59:56)
>>> import gnupg
>>> gpg = gnupg.GPG()
>>> plaintext = "No justice, no peace"
>>> type(plaintext)
<type 'str'>
>>> out = gpg.encrypt(plaintext, symmetric=True, passphrase="no racist police", encrypt=False)
>>> out.ok
True
>>> from StringIO import StringIO
>>> plaintext = StringIO("No justice, no peace")
>>> out = gpg.encrypt(plaintext, symmetric=True, passphrase="no racist police", encrypt=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/gnupg/gnupg.py", line 955, in encrypt
    stream = _make_binary_stream(data, self._encoding)
  File "/usr/local/lib/python2.7/dist-packages/gnupg/_util.py", line 396, in _make_binary_stream
    s = s.encode(encoding)
AttributeError: StringIO instance has no attribute 'encode'
```

There are numerous references to files and file-like objects in the docstrings of these functions, which leads me to believe this is supposed to work. It did work when using `encrypt_file` in 1.2.5, but it was broken when encrypt_file was changed to be `encrypt` in 295d98fbdc6a9bff927da8fe011241d7bbbd8a3c.

A closer look at the site of the traceback shows:

1. If the input to `encrypt` is a byte string (definition of that depends on Python 2.x or 3.x), it is wrapped in either a BytesIO or a StringIO and returned.
2. Otherwise, it is first encoded (default is `utf-8`), then converted into a stream object and returned.

Therefore, it seems that if `data` is *already* a stream object, we should simply return it rather than trying (and failing) to encode it - which doesn't really make sense for a stream object anyway.

The most obvious fix would be something like:

```py
            if type(s) not in (str, StringIO, BytesIO): # etc.
                s = s.encode(encoding)
```

Does that seem reasonable, or am I missing something?

**Comment by isislovecruft** [comment]
This should be fixed in 2.0.1 (because #92 is merged).
